# Generated by Django 6.0.3 on 2026-03-31 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=20)),
                ('account_password', models.CharField(max_length=20)),
                ('creation_date', models.DateTimeField(verbose_name='date created')),
            ],
        ),
    ]
