# Generated by Django 6.0.3 on 2026-03-31 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='creator',
            new_name='author',
        ),
    ]
